# Generated by Django 5.2.4 on 2025-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
