# Generated by Django 5.2.4 on 2025-09-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_is_wishlist_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
